# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master


variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'hellowworkressourcegroup'
    KeyVaultName: 'ContrastKeys-SaaS'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'hellowworkressourcegroup'
    Action: 'Install Extensions'
    WebAppName: 'helloworldIBM'
    ExtensionsList: 'Contrast.NetCore.Azure.SiteExtension'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    AppSettings: '-CONTRAST__API__USER_NAME $(CONTRAST-AGENT-USERNAME) -CONTRAST__API__API_KEY $(CONTRAST-API-KEY) -CONTRAST__API__SERVICE_KEY $(AGENT-API-SERVICE-KEY) -CONTRAST__API__URL https://eval.contrastsecurity.com/'
    azureSubscription: 'hellowworkressourcegroup'
    WebAppName: 'helloworldIBM'
    appType: 'webApp'
